export default {
  'agent-board': 'Agent Board',
  commands: 'Comandos',
  'cross-session-protocol': 'Protocolo entre sessões',
  'code-review': 'Revisão de código',
  'followup-suggestions': 'Sugestões de acompanhamento',
  'tool-use-summaries': 'Resumos de uso de ferramentas',
  'sub-agents': 'Subagentes',
  arena: 'Arena de agentes',
  skills: 'Habilidades',
  rules: 'Regras',
  memory: 'Memória',
  headless: 'Modo sem interface gráfica',
  'dual-output': 'Saída Dupla',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Modo de aprovação',
  mcp: 'MCP',
  lsp: 'LSP (Protocolo do Servidor de Linguagem)',
  'token-caching': 'Armazenamento em cache de tokens',
  'context-cost': 'Custo do contexto residente',
  sandbox: 'Sandbox',
  language: 'i18n',
  channels: 'Canais',
  hooks: 'Hooks',
  'status-line': 'Linha de status',
  'scheduled-tasks': 'Tarefas agendadas',
  'auto-mode': 'Modo Automático',
  'computer-use': 'Uso do Computador',
  'browser-use': 'Browser Use',
  goals: 'Objetivos',
  'markdown-rendering': 'Renderização de Markdown',
  'multi-agent-coordination': 'Coordenação Multiagente',
  'output-styles': 'Estilos de Saída',
  'structured-output': 'Saída Estruturada',
  'terminal-images': 'Imagens no Terminal',
  worktree: 'Worktrees',
  tips: 'Dicas Contextuais',
};
