export default {
  commands: 'Comandos',
  'cross-session-protocol': 'Protocolo entre sessões',
  'code-review': 'Revisão de código',
  'followup-suggestions': 'Sugestões de acompanhamento',
  'tool-use-summaries': 'Resumos de uso de ferramentas',
  'sub-agents': 'Subagentes',
  arena: 'Arena de Agentes',
  skills: 'Skills',
  memory: 'Memória',
  headless: 'Modo Headless',
  'dual-output': 'Saída Dupla',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Modo de Aprovação',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': 'Cache de Tokens',
  sandbox: 'Sandboxing',
  language: 'i18n',
  channels: 'Canais',
  hooks: 'Hooks',
  'status-line': 'Linha de Status',
  'scheduled-tasks': 'Tarefas Agendadas',
  'auto-mode': 'Modo Automático',
  'computer-use': 'Uso do Computador',
  goals: 'Objetivos',
  'markdown-rendering': 'Renderização de Markdown',
  'multi-agent-coordination': 'Coordenação Multiagente',
  'output-styles': 'Estilos de Saída',
  'structured-output': 'Saída Estruturada',
  'terminal-images': 'Imagens no Terminal',
  worktree: 'Worktrees',
  tips: 'Dicas Contextuais',
};