export default {
  commands: 'Commands',
  'cross-session-protocol': 'Cross-Session Protocol',
  'code-review': 'Code Review',
  'followup-suggestions': 'Followup Suggestions',
  'tool-use-summaries': 'Tool-Use Summaries',
  'sub-agents': 'SubAgents',
  arena: 'Agent Arena',
  skills: 'Skills',
  memory: 'Memory',
  headless: 'Headless Mode',
  'dual-output': 'Dual Output',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Approval Mode',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': 'Token Caching',
  sandbox: 'Sandboxing',
  language: 'i18n',
  channels: 'Channels',
  hooks: 'Hooks',
  'status-line': 'Status Line',
  'scheduled-tasks': 'Scheduled Tasks',
  'auto-mode': 'Auto Mode',
  'computer-use': 'Computer Use',
  goals: 'Goals',
  'markdown-rendering': 'Markdown Rendering',
  'multi-agent-coordination': 'Multi-Agent Coordination',
  'output-styles': 'Output Styles',
  'structured-output': 'Structured Output',
  'terminal-images': 'Terminal Images',
  worktree: 'Worktrees',
  tips: 'Contextual Tips',
};
