export default {
  'agent-board': 'Agent Board',
  commands: 'Commandes',
  'cross-session-protocol': 'Protocole inter-sessions',
  'code-review': 'Révision de code',
  'followup-suggestions': 'Suggestions de suivi',
  'tool-use-summaries': "Résumés d'utilisation des outils",
  'sub-agents': 'Sous-agents',
  arena: 'Arène des agents',
  skills: 'Compétences',
  rules: 'Règles',
  memory: 'Mémoire',
  headless: 'Mode sans interface graphique',
  'dual-output': 'Double sortie',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Mode d\'approbation',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': 'Mise en cache des jetons',
  'context-cost': 'Coût du contexte résident',
  sandbox: 'Bac à sable',
  language: 'i18n',
  channels: 'Canaux',
  hooks: 'Hooks',
  'status-line': 'Ligne d\'état',
  'scheduled-tasks': 'Tâches planifiées',
  'auto-mode': 'Mode automatique',
  'computer-use': "Utilisation de l'ordinateur",
  'browser-use': 'Browser Use',
  goals: 'Objectifs',
  'markdown-rendering': 'Rendu Markdown',
  'multi-agent-coordination': 'Coordination multi-agents',
  'output-styles': 'Styles de sortie',
  'structured-output': 'Sortie structurée',
  'terminal-images': 'Images de terminal',
  worktree: 'Worktrees',
  tips: 'Astuces contextuelles',
};
