export default {
  commands: '명령어',
  'cross-session-protocol': '크로스 세션 프로토콜',
  'code-review': '코드 리뷰',
  'followup-suggestions': '후속 제안',
  'tool-use-summaries': '도구 사용 요약',
  'sub-agents': '서브 에이전트',
  arena: '에이전트 아레나',
  skills: '스킬',
  memory: '메모리',
  headless: '헤드리스 모드',
  'dual-output': '이중 출력',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '승인 모드',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': '토큰 캐싱',
  sandbox: '샌드박싱',
  language: 'i18n',
  channels: '채널',
  hooks: '훅',
  'status-line': '상태 표시줄',
  'scheduled-tasks': '예약된 작업',
  'auto-mode': '자동 모드',
  'computer-use': '컴퓨터 사용',
  goals: '목표',
  'markdown-rendering': '마크다운 렌더링',
  'multi-agent-coordination': '멀티 에이전트 조율',
  'output-styles': '출력 스타일',
  'structured-output': '구조화된 출력',
  'terminal-images': '터미널 이미지',
  worktree: '워크트리',
  tips: '컨텍스트 팁',
};