export default {
  commands: 'Команды',
  'code-review': 'Проверка кода',
  'followup-suggestions': 'Последующие предложения',
  'sub-agents': 'Подагенты',
  arena: 'Арена агентов',
  skills: 'Навыки',
  headless: 'Безголовый режим',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Режим подтверждения',
  mcp: 'MCP',
  lsp: 'LSP (протокол сервера языка)',
  'token-caching': 'Кэширование токенов',
  sandbox: 'Песочница',
  language: 'i18n',
  channels: 'Каналы',
  hooks: 'Хуки',
  'status-line': 'Строка состояния',
  'scheduled-tasks': 'Запланированные задачи',
};