export default {
  commands: 'Команды',
  'cross-session-protocol': 'Кросс-сессийный протокол',
  'code-review': 'Проверка кода',
  'followup-suggestions': 'Последующие предложения',
  'tool-use-summaries': 'Сводки по использованию инструментов',
  'sub-agents': 'Подагенты',
  arena: 'Арена агентов',
  skills: 'Навыки',
  memory: 'Память',
  headless: 'Безголовый режим',
  'dual-output': 'Двойной вывод',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Режим подтверждения',
  mcp: 'MCP',
  lsp: 'LSP (протокол сервера языка)',
  'token-caching': 'Кэширование токенов',
  sandbox: 'Песочница',
  language: 'i18n',
  channels: 'Каналы',
  hooks: 'Хуки',
  'status-line': 'Строка состояния',
  'scheduled-tasks': 'Запланированные задачи',
  'auto-mode': 'Автоматический режим',
  'computer-use': 'Управление компьютером',
  goals: 'Цели',
  'markdown-rendering': 'Рендеринг Markdown',
  'multi-agent-coordination': 'Мультиагентная координация',
  'output-styles': 'Стили вывода',
  'structured-output': 'Структурированный вывод',
  'terminal-images': 'Изображения в терминале',
  worktree: 'Рабочие деревья',
  tips: 'Контекстные подсказки',
};