export default {
  commands: '命令',
  'code-review': '代码审查',
  'followup-suggestions': '后续建议',
  'sub-agents': '子智能体',
  arena: '智能体竞技场',
  skills: '技能',
  headless: '无头模式',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '审批模式',
  mcp: 'MCP',
  lsp: 'LSP（语言服务器协议）',
  'token-caching': 'Token 缓存',
  sandbox: '沙箱',
  language: '国际化 (i18n)',
  channels: '频道',
  hooks: '钩子',
  'status-line': '状态行',
  'scheduled-tasks': '定时任务',
};