export default {
  commands: '命令',
  'cross-session-protocol': '跨会话协议',
  'code-review': '代码审查',
  'followup-suggestions': '后续建议',
  'tool-use-summaries': '工具使用摘要',
  'sub-agents': '子智能体',
  arena: '智能体竞技场',
  skills: '技能',
  memory: '记忆',
  headless: '无头模式',
  'dual-output': '双输出',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '审批模式',
  mcp: 'MCP',
  lsp: 'LSP（语言服务器协议）',
  'token-caching': 'Token 缓存',
  sandbox: '沙箱',
  language: '国际化 (i18n)',
  channels: '频道',
  hooks: '钩子',
  'status-line': '状态行',
  'scheduled-tasks': '定时任务',
  'auto-mode': '自动模式',
  'computer-use': '计算机使用',
  goals: '目标',
  'markdown-rendering': 'Markdown 渲染',
  'multi-agent-coordination': '多智能体协同',
  'output-styles': '输出样式',
  'structured-output': '结构化输出',
  'terminal-images': '终端图像',
  worktree: '工作树',
  tips: '上下文提示',
};