export default {
  commands: 'Befehle',
  'cross-session-protocol': 'Cross-Session-Protokoll',
  'code-review': 'Code-Überprüfung',
  'followup-suggestions': 'Follow-up-Vorschläge',
  'tool-use-summaries': 'Tool-Use-Zusammenfassungen',
  'sub-agents': 'Subagents',
  arena: 'Agent-Arena',
  skills: 'Fähigkeiten',
  memory: 'Memory',
  headless: 'Headless-Modus',
  'dual-output': 'Dual Output',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': 'Genehmigungsmodus',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': 'Token-Caching',
  sandbox: 'Sandboxing',
  language: 'i18n',
  channels: 'Kanäle',
  hooks: 'Hooks',
  'status-line': 'Statuszeile',
  'scheduled-tasks': 'Geplante Aufgaben',
  'auto-mode': 'Auto-Modus',
  'computer-use': 'Computer Use',
  goals: 'Ziele',
  'markdown-rendering': 'Markdown-Rendering',
  'multi-agent-coordination': 'Multi-Agent-Koordination',
  'output-styles': 'Ausgabestile',
  'structured-output': 'Strukturierte Ausgabe',
  'terminal-images': 'Terminal-Bilder',
  worktree: 'Worktrees',
  tips: 'Kontextbezogene Tipps',
};