export default {
  commands: 'コマンド',
  'code-review': 'コードレビュー',
  'followup-suggestions': 'フォローアップの提案',
  'sub-agents': 'サブエージェント',
  arena: 'エージェントアリーナ',
  skills: 'スキル',
  headless: 'ヘッドレスモード',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '承認モード',
  mcp: 'MCP',
  lsp: 'LSP（言語サーバープロトコル）',
  'token-caching': 'トークンキャッシュ',
  sandbox: 'サンドボックス',
  language: 'i18n',
  channels: 'チャンネル',
  hooks: 'フック',
  'status-line': 'ステータスライン',
  'scheduled-tasks': 'スケジュールタスク',
};