export default {
  commands: 'コマンド',
  'cross-session-protocol': 'クロスセッションプロトコル',
  'code-review': 'コードレビュー',
  'followup-suggestions': 'フォローアップ提案',
  'tool-use-summaries': 'ツール使用の概要',
  'sub-agents': 'サブエージェント',
  arena: 'エージェントアリーナ',
  skills: 'スキル',
  memory: 'メモリ',
  headless: 'ヘッドレスモード',
  'dual-output': 'デュアル出力',
  checkpointing: {
    display: 'hidden',
  },
  'approval-mode': '承認モード',
  mcp: 'MCP',
  lsp: 'LSP (Language Server Protocol)',
  'token-caching': 'トークンキャッシング',
  sandbox: 'サンドボックス',
  language: 'i18n',
  channels: 'チャンネル',
  hooks: 'フック',
  'status-line': 'ステータスライン',
  'scheduled-tasks': 'スケジュールタスク',
  'auto-mode': '自動モード',
  'computer-use': 'コンピュータ操作',
  goals: '目標',
  'markdown-rendering': 'Markdownレンダリング',
  'multi-agent-coordination': 'マルチエージェント協調',
  'output-styles': '出力スタイル',
  'structured-output': '構造化出力',
  'terminal-images': 'ターミナル画像',
  worktree: 'ワークツリー',
  tips: 'コンテキストヒント',
};